1. Write a program on data pre-processing including analysis on
the dataset, pre-process on null dataset, what is dirty data set
and how to handle continues values.

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving house_price_regression_dataset.csv to house_price_regression_dataset.csv


In [ ]:
import pandas as pd

# Load the dataset
data = pd.read_csv("house_price_regression_dataset.csv")

  # Replace 'your_dataset.csv' with the actual file path

# Display basic information about the dataset
print(data.info())  # Shows data types, non-null values, etc.
print(data.describe())  # Provides descriptive statistics
print(data.head())  # Displays the first few rows of the dataset



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Square_Footage        1000 non-null   int64  
 1   Num_Bedrooms          1000 non-null   int64  
 2   Num_Bathrooms         1000 non-null   int64  
 3   Year_Built            1000 non-null   int64  
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64  
 6   Neighborhood_Quality  1000 non-null   int64  
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB
None
       Square_Footage  Num_Bedrooms  Num_Bathrooms   Year_Built     Lot_Size  \
count     1000.000000   1000.000000    1000.000000  1000.000000  1000.000000   
mean      2815.422000      2.990000       1.973000  1986.550000     2.778087   
std       1255.514921      1.427564       0.820332    20.632916     1.297903   
min      

In [ ]:
import pandas as pd

# Step 1: Load the dataset
data = pd.read_csv("house_price_regression_dataset.csv")

# Step 2: Basic information about the dataset
print("=== Dataset Info ===")
print(data.info())

print("\n=== Statistical Summary ===")
print(data.describe())

print("\n=== First 5 Rows ===")
print(data.head())

# Step 3: Check for missing values
print("\n=== Missing Values Per Column ===")
print(data.isnull().sum())

# Step 4: Handle missing values (impute with mean for numerical columns)
num_cols = data.select_dtypes(include=['float64', 'int64']).columns
for col in num_cols:
    if data[col].isnull().sum() > 0:
        data[col] = data[col].fillna(data[col].mean())
        print(f"Filled missing values in '{col}' with its mean.")

# Step 5: Confirm no missing values remain
print("\n=== Missing Values After Imputation ===")
print(data.isnull().sum())

# Step 6: Unique values in categorical/ordinal columns (if any)
print("\n=== Unique values in 'Neighborhood_Quality' ===")
print(data['Neighborhood_Quality'].unique())
print(data['Neighborhood_Quality'].value_counts())


=== Dataset Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Square_Footage        1000 non-null   int64  
 1   Num_Bedrooms          1000 non-null   int64  
 2   Num_Bathrooms         1000 non-null   int64  
 3   Year_Built            1000 non-null   int64  
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64  
 6   Neighborhood_Quality  1000 non-null   int64  
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB
None

=== Statistical Summary ===
       Square_Footage  Num_Bedrooms  Num_Bathrooms   Year_Built     Lot_Size  \
count     1000.000000   1000.000000    1000.000000  1000.000000  1000.000000   
mean      2815.422000      2.990000       1.973000  1986.550000     2.778087   
std       1255.514921      1.427564    

In [ ]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Step 1: Load Titanic Dataset
df = sns.load_dataset("titanic")

# Select relevant columns for machine learning
df = df[['survived', 'pclass', 'sex', 'age', 'fare', 'embarked']]

# Step 2: Handle Missing Data

## 2.1 Impute missing numerical values with the mean
num_imputer = SimpleImputer(strategy='mean')
df[['age', 'fare']] = num_imputer.fit_transform(df[['age', 'fare']])

## 2.2 Impute missing categorical values with the most frequent value (mode)
cat_imputer = SimpleImputer(strategy='most_frequent')
df[['embarked']] = cat_imputer.fit_transform(df[['embarked']])

# Step 3: Encode Categorical Data (Convert text labels into numbers)
label_encoder = LabelEncoder()
df['sex'] = label_encoder.fit_transform(df['sex']) # Male=1, Female=0
df['embarked'] = label_encoder.fit_transform(df['embarked']) # C, Q, S → 0,1,2

# Step 4: Split Dataset into Training and Testing Sets
X = df.drop(columns=["survived"]) # Features
y = df["survived"] # Target variable (0 = Did not survive, 1 = Survived)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Step 5: Feature Scaling (Standardize numerical features)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Output Analysis
print("Processed Training Data (First 10 Rows):\n", X_train[:10])
print("Processed Testing Data (First 10 Rows):\n", X_test[:10])

Processed Training Data (First 10 Rows):
 [[-1.61413602  0.7243102   1.22920747 -0.07868358  0.5635246 ]
 [-0.40055118  0.7243102  -0.50350514 -0.37714494  0.5635246 ]
 [ 0.81303367  0.7243102   0.18957991 -0.47486697  0.5635246 ]
 [ 0.81303367  0.7243102  -0.27247679 -0.47623026  0.5635246 ]
 [ 0.81303367 -1.38062393 -1.81266577 -0.02524937  0.5635246 ]
 [-1.61413602  0.7243102  -0.42649569  4.13868709 -2.02505292]
 [-1.61413602  0.7243102   1.19070275 -0.11623195  0.5635246 ]
 [-0.40055118  0.7243102  -0.04144844 -0.09368752 -2.02505292]
 [ 0.81303367  0.7243102   0.01239022 -0.47542923  0.5635246 ]
 [-1.61413602  0.7243102   0.01239022  0.05610542  0.5635246 ]]
Processed Testing Data (First 10 Rows):
 [[ 0.81303367  0.7243102   0.01239022 -0.33390078 -2.02505292]
 [-0.40055118  0.7243102   0.11257046 -0.42528387  0.5635246 ]
 [ 0.81303367  0.7243102  -0.73453348 -0.47486697  0.5635246 ]
 [-0.40055118 -1.38062393 -1.81266577  0.00796649  0.5635246 ]
 [ 0.81303367 -1.38062393 -1.19659

<ipython-input-11-668e572b3fe6>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['age', 'fare']] = num_imputer.fit_transform(df[['age', 'fare']])
<ipython-input-11-668e572b3fe6>:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['embarked']] = cat_imputer.fit_transform(df[['embarked']])
<ipython-input-11-668e572b3fe6>:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the document